### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by zampage** [skills17/cypress-helpers#2]
Could we provide windows-compatibility for this package?
I believe the error I'm getting is because of `$(npm bin)`, which could potentially be solved by just removing and having only `cypress [...]` if my understanding of this is correct.

![image](https://user-images.githubusercontent.com/18336255/104851069-f1faaf80-58f2-11eb-8e49-fb4b8c874cd5.png)

**Comment by zampage** [comment]
Changing the line that generates the command to the following worked for me on windows.

```js
const command = `cypress ${this.buildCypressArgs().join(' ')}`;
```

- Problem 1: `$(npm bin)` didn't work as previously stated - solved by removing since the execution context knows of the cypress command if cypress is installed locally
- Problem 2: ` _shellEscape.default` tried to but parentheses around some arguments which my shell didn't like, solved for now by replacing it with joining the arguments manually

![image](https://user-images.githubusercontent.com/18336255/104851975-6dab2b00-58f8-11eb-9b03-6ca7b5a50828.png)

**Comment by cyrilwanner** [comment]
Thanks for the issue, the packages may indeed not support windows yet since I didn't have time to test them there yet, but I'm glad for every bug report!

* Problem 1: `$(npm bin)` shouldn't be needed as you wrote, because we are already in an npm environment, so the bin folder is already appended to the PATH anyway
* Problem 2: I'll replace the escaping library with one that also supports windows. I think we should still do it there for security reasons but also to prevent unexpected behavior.

I'll notify you when a new version is ready to test :)

**Comment by cyrilwanner** [comment]
Patch `v1.0.1` should resolve the windows issues while still preserving all features. Can you try it again with that version?

**Comment by zampage** [comment]
The patch works well! Many thanks! 😃 🚀
