### ISSUE TITLE
Improved recommended NPM run-scripts in README.md

### ISSUE THREAD

**Issue by sebastianhaeni** [skills17/cypress-helpers#3]
The README.md currently suggests these run-scripts to run the tests:

```json
  "scripts": {
    "start": "skills17-cypress open",
    "test": "skills17-cypress run --quiet",
    "test:json": "skills17-cypress run --quiet --json"
  },
```

For the automated tests, this will run in Electron and in the timezone the machine is configured to.

I suggest to update this to the following:

```json
    "scripts": {
        "start": "TZ=Etc/UTC skills17-cypress open --browser chrome",
        "test": "TZ=Etc/UTC skills17-cypress run --quiet --browser chrome",
        "test:json": "TZ=Etc/UTC skills17-cypress run --quiet --json --browser chrome --headless"
    },
```

What do you think?

The `start` script unfortunately doesn't select Chrome if the user has manually selected another browser in a previous session. I just put it there for consistency and for first time runs.

The timezone is important since the browser will display dates and times differently depending on the timezone.

**Comment by cyrilwanner** [comment]
Thanks! This just reminds me that I've forgotten to use Chrome instead of Electron at the regional skills. So it totally makes sense to add the browser to the recommended commands 👍 

> The start script unfortunately doesn't select Chrome if the user has manually selected another browser in a previous session.

I actually think this isn't a bad thing. Because it allows competitors to also run the tests in Firefox when it is specified that the webpage should work in both Chrome & Firefox.


For the timezone, I would suggest some changes:
- By default, scripts are executed in cmd on Windows which does not support environment variables in this format. Since some competitions use Windows (EuroSkills/WorldSkills), the commands will fail there.
  - But what we could do is to add a new cli parameter (like `--timezone Etc/UTC`) that sets the environment variable in our command wrapper (we already set some others there) so it will also work on Windows. Then, we could specify it in the Readme [next to the other arguments](https://github.com/skills17/cypress-helpers#cli).
- I think it would be better to set the timezone to the one in which the competition takes place.
  - That way, the competitors see the same times in their browser and in Cypress. It could be confusing when different dates are displayed for the same data.
  - For competitions in completely different timezones, for example if they build a restaurant page, restaurants would open at midnight instead of 18:00.
  - If the timezone is set to UTC, competitors could (more or less) just return the date string instead of parsing it to a date instance (which I consider best practice).


What do you think about those timezone changes?

**Comment by sebastianhaeni** [comment]
Windows env problem: Yes true. Your proposition sounds good. An alternative would be to use [cross-env](https://www.npmjs.com/package/cross-env). Example:
```
 "start": "cross-env TZ=Etc/UTC skills17-cypress open --browser chrome",
```

--- 

Yes, that makes sense to set it to the local timezone. However, the person writing the tests in a different timezone will then have this problem of the restaurant opening at midnight :) But this can be neglected. 

I think it should be decided per competition. If we would ever have a competition where competitors participate from different timezones, UTC might make sense again.

But to avoid issues it should be consistently set and thus recommended in the README.md.

**Comment by cyrilwanner** [comment]
True, `cross-env` would also work. But since we already have our own command wrapper around cypress, I simply implemented it there. This way, we can avoid additional dependencies and complex commands.

You can now use it like this (v2.1.0 was just published):
```
skills17-cypress open --browser chrome --timezone Etc/UTC
```

**Comment by sebastianhaeni** [comment]
Awesome! I'm closing this issue then.
